# -*- coding: utf-8 -*-
"""EvenorOdd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qug2N1FwQ-hKh2Iw5l3yBXjECARfVr5C
"""

num=int(input("Enter a number::"))
if num>=0:
  if num%2==0:
    print("even")
  else:
    print("Odd")
else:
  print("is -ve")