# -*- coding: utf-8 -*-
"""Modifylistwith3500.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOJopUXaEbkPMuGUsp1UMi-m584hUDLt
"""

list = [5, [10, 15, [20, 25, [30, 35], 40], 45], 50]

list[1][2][2][1] = 3500
print(list)



