# -*- coding: utf-8 -*-
"""String_Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EAicbjBTzeYKUkRdutp8tf7BQLXj6BdI
"""

str="Anilkumar S V"
print(str)

print(str[0:])
print(str[1:])
print(str[2:5])
print(str[5:13])

print(str.islower())
print(str.capitalize())
print(str.isspace())
print(str.isupper())
print(str.isprintable())
print(str.isnumeric())
print(str.swapcase())
print(str.title())
print(str.upper())
print(str.lower())
print(str.rstrip())



















